apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: ejb-timer
  name: ejb-timer
spec:
  replicas: 1
  selector:
    deploymentconfig: ejb-timer
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: ejb-timer
        deploymentconfig: ejb-timer
    spec:
      containers:
      - image: 172.30.1.1:5000/eap-splunk-sidecar/ejb-timer@sha256:9c97fd2966b3b7a99853ba464a953f53ec7b26c501466708e605ed4ad91f369f
        imagePullPolicy: Always
        name: ejb-timer
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /opt/eap/standalone/log
          name: eap-log-volume
      - env:
        - name: SPLUNK_SERVER
          value: <insert-splunk-host>:9997
        - name: SPLUNK_MONITOR_LOCN
          value: /opt/eap/standalone/log
        - name: SPLUNK_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: splunk-credentials
        - name: SPLUNK_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: splunk-credentials
        - name: OCP_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: 172.30.1.1:5000/eap-splunk-sidecar/splunk-forwarder@sha256:cb7b914bdfbae889ea66e2ac21fc1725e851c3f7eeece44ec3a581ab7f6e6754
        imagePullPolicy: Always
        name: splunk-forwarder
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /opt/eap/standalone/log
          name: eap-log-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: eap-log-volume
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - ejb-timer
      from:
        kind: ImageStreamTag
        name: ejb-timer:latest
        namespace: eap-splunk-sidecar
    type: ImageChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - splunk-forwarder
      from:
        kind: ImageStreamTag
        name: splunk-forwarder:latest
        namespace: eap-splunk-sidecar
    type: ImageChange
  - type: ConfigChange
